version: "2"
services:
  # the database image
  db:
    image: "postgres:9.4"
    environment:
      POSTGRES_USER: kitteh
      POSTGRES_PASSWORD: kitteh
      # this is not used properly at the moment
      POSTGRES_DB: kitteh_prod
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgres

  # for serving assets
  nginx:
    build:
      context: "."
      dockerfile: "./Dockerfile.nginx"
    volumes:
      - assets:/var/uploads
    ports:
      - "4001:80"

  # the main image, this is the application
  web:
    build: "."
    environment:
      PORT: "4000"
      MIX_ENV: "prod"
    ports:
      - "4000:4000"
    links:
      - "db:db"
    volumes:
      - assets:/var/uploads

volumes:
  # for persistance of database data
  dbdata:
    driver: local

  # for keeping assets
  assets:
    driver: local